# Generated by Django 5.2.5 on 2025-09-26 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='paid_fee',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='total_fee',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
