# Generated by Django 5.2.5 on 2025-09-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_student_paid_fee_alter_student_total_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='paid_fee',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='student',
            name='total_fee',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
